name = "knowscape-api"
main = "workers/index.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "knowscape-db"
database_id = "6e0bb22d-1a1d-4b5b-a647-f2306e991baf"

[vars]
JWT_SECRET = "knowscape-jwt-secret-2026"
DEEPSEEK_API_KEY = "sk-placeholder-replace-me"
